import { PrimingExercise, WorkoutSession } from '../types/thp';

export const THP_WORKOUT_DATABASE: WorkoutSession[] = [
  // 1. SESSÃO MAX EFFORT LOWER (FORÇA MÁXIMA & BASE CONCÊNTRICA)
  {
    id: 'thp_max_effort_lower',
    title: 'Conjugado Longo: Max Effort Lower',
    subtitle: 'Sobrecarga Neural & Recrutamento de Unidades Motoras Tipo IIx',
    phase: 'ACCUMULATION_VOLUME',
    dayType: 'Max Effort Lower',
    targetDeficit: 'FORCE_DEFICIT',
    estimatedMinutes: 65,
    intensityDescription: 'Alta Intensidade Neural (RPE 8.5 - 9.5) / Baixo Volume de Fadiga',
    rationale: 'O salto vertical requer enorme impulso em milissegundos. Sem força base no agachamento (1.8x - 2.2x BW), a aceleração do centro de gravidade atinge um teto intransponível.',
    exercises: [
      {
        id: 'ex_1',
        name: 'Spanish Squat Hold (Isometria Analgésica de Tendão)',
        category: 'TENDON_ISOMETRIC',
        sets: 4,
        reps: '45 segundos hold',
        tempo: 'Isometria contínua a 70° flexão de joelho',
        restSeconds: 60,
        targetRpe: 7,
        cues: 'Prenda o elástico pesado atrás dos joelhos em uma coluna fixa. Sente para trás a 70-80 graus de flexão. Mantenha tronco vertical. Isso descarrega a patela e estimula o remodelamento de colágeno sem cisalhamento.',
        tendonFriendly: true,
        intensityLevel: 'Submaximal',
      },
      {
        id: 'ex_2',
        name: 'Barbell Back Squat com Pausa de 2 Segundos',
        category: 'MAX_STRENGTH',
        sets: 4,
        reps: '3 repetições @ 85% 1RM',
        tempo: '2s pausa no fundo, explosão concêntrica máxima',
        restSeconds: 150,
        targetRpe: 8.5,
        cues: 'Desça sob controle até a paralela. PARE por 2 segundos completos para dissipar energia elástica passiva e forçar recrutamento concêntrico puro. Exploda para cima com intenção máxima de velocidade (Max Intent).',
        tendonFriendly: true,
        intensityLevel: 'Max Effort',
      },
      {
        id: 'ex_3',
        name: 'Trap Bar Deadlift (Puxada Explosiva)',
        category: 'MAX_STRENGTH',
        sets: 3,
        reps: '4 repetições @ 80% 1RM',
        tempo: 'Reset a cada repetição no chão',
        restSeconds: 120,
        targetRpe: 8,
        cues: 'Trave escápulas e abdômen. Pressione o chão com os calcanhares e mediopé. Foque na extensão violenta de quadril nos últimos 30% do movimento.',
        tendonFriendly: true,
        intensityLevel: 'High',
      },
      {
        id: 'ex_4',
        name: 'Depth Jump para Box (Transferência de Força com Absorção)',
        category: 'PLYOMETRIC_SSC',
        sets: 4,
        reps: '4 saltos de caixa (30cm para caixa de 40cm)',
        tempo: 'Tempo de contato mínimo (< 200ms)',
        restSeconds: 90,
        targetRpe: 8.5,
        cues: 'Caia da caixa de 30cm com os dois pés simultâneos e rebata IMEDIATAMENTE para a caixa da frente. Pense em "o chão é lava". Não deixe o calcanhar colapsar no solo.',
        tendonFriendly: false,
        intensityLevel: 'Max Effort',
      },
      {
        id: 'ex_5',
        name: 'Seated Dumbbell Calf Raise (Foco no Sóleo)',
        category: 'TENDON_ISOMETRIC',
        sets: 3,
        reps: '12 repetições com 3s pausa isométrica no topo',
        tempo: '3s topo - 2s descida',
        restSeconds: 60,
        targetRpe: 8,
        cues: 'O músculo sóleo absorve até 8x o peso corporal no apoio de salto. Joelhos dobrados a 90° isolam o sóleo em vez dos gastrocnêmios.',
        tendonFriendly: true,
        intensityLevel: 'Submaximal',
      },
    ],
  },

  // 2. SESSÃO DYNAMIC EFFORT & REACTIVITY (ELASTICIDADE & SSC)
  {
    id: 'thp_dynamic_effort_ssc',
    title: 'Conjugado Longo: Dynamic Effort & SSC',
    subtitle: 'Taxa de Desenvolvimento de Força (RFD) & Rigidez Tendínea Reativa',
    phase: 'TRANSMUTATION_FORCE',
    dayType: 'Dynamic Effort Plyo',
    targetDeficit: 'ELASTICITY_SSC_DEFICIT',
    estimatedMinutes: 55,
    intensityDescription: 'Máxima Velocidade de Barra & Pliometria de Alto Impacto Reativo',
    rationale: 'Para atletas com déficit de elasticidade (EUR < 1.08), o tendão precisa aprender a deformar e retornar energia mecânica instantânea via reflexo miotático.',
    exercises: [
      {
        id: 'ex_dyn_1',
        name: 'Single-Leg Wall Sit Hold com Calcanhar Elevado',
        category: 'TENDON_ISOMETRIC',
        sets: 3,
        reps: '35 segundos por perna',
        tempo: 'Isometria estática',
        restSeconds: 45,
        targetRpe: 7,
        cues: 'Costas na parede, 90° de joelho. Eleve o calcanhar 2cm do chão (ativação plantar e tendão de Aquiles simultânea ao patelar). Mantenha pelve nivelada.',
        tendonFriendly: true,
        intensityLevel: 'Submaximal',
      },
      {
        id: 'ex_dyn_2',
        name: 'Speed Squat com Elástico (Accommodating Resistance)',
        category: 'DYNAMIC_POWER',
        sets: 6,
        reps: '2 repetições @ 55% 1RM + Elásticos',
        tempo: 'Descida rápida controlada, aceleração explosiva máxima',
        restSeconds: 60,
        targetRpe: 7.5,
        cues: 'O elástico força aceleração contínua até o topo sem desaceleração prematura. Se o tempo da repetição passar de 0.6 segundos, reduza a carga.',
        tendonFriendly: true,
        intensityLevel: 'High',
      },
      {
        id: 'ex_dyn_3',
        name: 'Continuous Ankling & Pogo Jumps Reativos',
        category: 'PLYOMETRIC_SSC',
        sets: 4,
        reps: '15 saltos contínuos',
        tempo: 'Tornozelos travados em 90°, contato puramente antepé',
        restSeconds: 75,
        targetRpe: 8,
        cues: 'Não dobre os joelhos mais que 15°. Os saltos vêm unicamente da rigidez do complexo Aquiles-Sóleo. Busque altura máxima mantendo som seco e rápido no chão.',
        tendonFriendly: true,
        intensityLevel: 'High',
      },
      {
        id: 'ex_dyn_4',
        name: 'Depth Jumps Reativos (Drop de 40cm)',
        category: 'PLYOMETRIC_SSC',
        sets: 5,
        reps: '3 drops com intenção máxima de altura vertical',
        tempo: 'Rebote instantâneo',
        restSeconds: 120,
        targetRpe: 9,
        cues: 'Passo para frente na borda da caixa, sem pular para cima ao descer. Ao tocar o solo, dispare os braços e o corpo em direção ao teto. Tempo de solo ideal < 0.18s.',
        tendonFriendly: false,
        intensityLevel: 'Max Effort',
      },
      {
        id: 'ex_dyn_5',
        name: 'Medicine Ball Overhead Slam com Tripla Extensão',
        category: 'DYNAMIC_POWER',
        sets: 3,
        reps: '6 repetições explosivas',
        tempo: 'Max Intent',
        restSeconds: 60,
        targetRpe: 7.5,
        cues: 'Transfira a potência dos pés, quadril e tronco até o arremesso para o chão. Conexão neuromuscular de cadeia posterior e anterior.',
        tendonFriendly: true,
        intensityLevel: 'High',
      },
    ],
  },

  // 3. SESSÃO TÉCNICA DO PENÚLTIMO PASSO & BLOQUEIO (MECHANICAL PEAKING)
  {
    id: 'thp_technique_penultimate',
    title: 'Mecânica do Salto: Penultimate Step Mastery',
    subtitle: 'Conversão Vetorial (Velocidade Horizontal para Vertical)',
    phase: 'REALIZATION_PEAKING',
    dayType: 'Technique & Jump Realization',
    targetDeficit: 'TECHNIQUE_MECHANICAL_DEFICIT',
    estimatedMinutes: 50,
    intensityDescription: 'Alta Precisão Técnica, Filmagens em Slow Motion & Coordenação de Braços',
    rationale: 'O penúltimo passo longo e rebaixado permite colocar o centro de gravidade atrás do pé de apoio, criando o ângulo ideal de projeção vertical sem perder velocidade horizontal.',
    exercises: [
      {
        id: 'ex_tech_1',
        name: 'Spanish Squat Isometric Hold com Rotação de Tronco',
        category: 'TENDON_ISOMETRIC',
        sets: 3,
        reps: '40 segundos',
        tempo: 'Isometria controlada',
        restSeconds: 60,
        targetRpe: 6.5,
        cues: 'Ativação do quadríceps e tendão patelar com foco no alinhamento do joelho em relação ao segundo dedo do pé.',
        tendonFriendly: true,
        intensityLevel: 'Submaximal',
      },
      {
        id: 'ex_tech_2',
        name: 'Penultimate Step Bounding Drill (Passo Penúltimo Agressivo)',
        category: 'PLYOMETRIC_SSC',
        sets: 5,
        reps: '4 repetições de entrada com aproximação de 2 passos',
        tempo: 'Penúltimo passo longo e baixo, pé de bloqueio rápido',
        restSeconds: 90,
        targetRpe: 8,
        cues: 'O penúltimo passo deve ser o mais longo e o mais rápido. Afunde o quadril, jogue os dois braços para trás (cocking) e finque o pé de bloqueio (block foot) ligeiramente à frente em 30-45 graus.',
        tendonFriendly: true,
        intensityLevel: 'High',
      },
      {
        id: 'ex_tech_3',
        name: 'Approach Max Vertical Jumps (Com Alvo no Aro/Tabela)',
        category: 'PLYOMETRIC_SSC',
        sets: 4,
        reps: '3 saltos com 100% intenção de toque no ponto mais alto',
        tempo: 'Descanso total entre tentativas para garantir frescor neural',
        restSeconds: 120,
        targetRpe: 9.5,
        cues: 'Aplique a técnica do drill anterior em alta velocidade. Mantenha os olhos fixos no ponto mais alto do aro. Dispare os braços sincronizados com a frenagem do pé dianteiro.',
        tendonFriendly: false,
        intensityLevel: 'Max Effort',
      },
      {
        id: 'ex_tech_4',
        name: 'Dumbbell Jump Squats Leves (Potência Rápida)',
        category: 'DYNAMIC_POWER',
        sets: 3,
        reps: '5 saltos com halteres de 10kg',
        tempo: 'Contramovimento rápido e decolagem',
        restSeconds: 90,
        targetRpe: 7.5,
        cues: 'Treina o sistema nervoso a superar inércia adicional sem comprometer a mecânica de decolagem.',
        tendonFriendly: true,
        intensityLevel: 'High',
      },
    ],
  },

  // 4. SESSÃO TENDON RESTORATION & REMODELING
  {
    id: 'thp_tendon_restoration',
    title: 'Tendon Health & Remodeling (Protocolo Analgésico)',
    subtitle: 'Inibição Cortical Motora & Síntese de Colágeno Tipo I',
    phase: 'ACCUMULATION_VOLUME',
    dayType: 'Tendon Restoration',
    targetDeficit: 'BALANCED_OPTIMIZED',
    estimatedMinutes: 45,
    intensityDescription: 'Baixo Impacto / Altas Isometrias Analgésicas / RPE 6-7',
    rationale: 'Protocolo baseado nos estudos da Dra. Jill Cook e do protocolo THP: isometrias pesadas sustentadas de 45 segundos produzem alívio imediato da dor por até 45 minutos e aumentam a tolerância mecânica do tendão.',
    exercises: [
      {
        id: 'ex_tend_1',
        name: 'Single-Leg Leg Extension Isometric Hold',
        category: 'TENDON_ISOMETRIC',
        sets: 5,
        reps: '45 segundos hold a 60 graus de flexão',
        tempo: 'Isometria constante @ 70% MVC',
        restSeconds: 90,
        targetRpe: 7.5,
        cues: 'Ajuste a máquina para que o joelho fique travado a 60 graus de flexão (ponto de máximo braço de alavanca do tendão patelar). Segure com força contínua sem tremer excessivamente.',
        tendonFriendly: true,
        intensityLevel: 'Submaximal',
      },
      {
        id: 'ex_tend_2',
        name: 'Spanish Squat Hold com Carga (Halter no Peito)',
        category: 'TENDON_ISOMETRIC',
        sets: 4,
        reps: '45 segundos hold',
        tempo: 'Estático',
        restSeconds: 90,
        targetRpe: 7,
        cues: 'Mantenha a tíbia o mais vertical possível. A tensão do elástico atrás da fossa poplítea elimina o estresse na articulação patelofemoral enquanto sobrecarrega positivamente o tendão.',
        tendonFriendly: true,
        intensityLevel: 'Submaximal',
      },
      {
        id: 'ex_tend_3',
        name: 'Seated Calf Isometric Hold (Sóleo Pesado)',
        category: 'TENDON_ISOMETRIC',
        sets: 4,
        reps: '45 segundos hold com carga moderada-alta',
        tempo: 'Estático na metade da amplitude',
        restSeconds: 60,
        targetRpe: 7,
        cues: 'Protege e remodela o tendão de Aquiles e a fáscia plantar. Fundamental para amortecimento em saltos de um e dois pés.',
        tendonFriendly: true,
        intensityLevel: 'Submaximal',
      },
      {
        id: 'ex_tend_4',
        name: 'Copenhagen Adductor Plank (Estabilidade Pélvica)',
        category: 'CORE_POSTURE',
        sets: 3,
        reps: '30 segundos por lado',
        tempo: 'Isometria estática',
        restSeconds: 45,
        targetRpe: 7,
        cues: 'Perna de cima apoiada no banco. Mantenha linha reta do ombro ao tornozelo. Fortalece adutores e estabiliza o valgo dinâmico de joelho no salto.',
        tendonFriendly: true,
        intensityLevel: 'Submaximal',
      },
    ],
  },
];

// MÓDULO GAME DAY PRIMING (PRÉ-JOGO: 12-24H ANTES DO JOGO)
export const THP_GAME_DAY_PRIMING_ROUTINE: PrimingExercise[] = [
  {
    id: 'prime_1',
    name: 'Pulso Térmico & Reatividade Suave (Corda ou Ankling)',
    phase: 'THERMAL_PULSE',
    durationSeconds: 180,
    sets: 1,
    repsOrHold: '3 minutos contínuos (ritmo moderado)',
    purpose: 'Elevar a temperatura dos tecidos conjuntivos e aumentar a velocidade de condução nervosa sem depletar glicogênio muscular.',
    instructions: 'Pulos ritmados, sem tocar os calcanhares no chão. Respiração nasal controlada.',
  },
  {
    id: 'prime_2',
    name: 'Spanish Squat Hold Analgésico Pré-Jogo',
    phase: 'TENDON_ANALGESIA',
    durationSeconds: 45,
    sets: 2,
    repsOrHold: '2 séries x 45 segundos hold',
    purpose: 'Diminuir a dor patelar através da inibição cortical motora e preparar os tendões para absorver forças de desaceleração no jogo.',
    instructions: 'Elástico grosso atrás dos joelhos, ângulo de 70-80° no joelho. Segure firme sem fadiga extrema.',
  },
  {
    id: 'prime_3',
    name: 'Overcoming Isometric Squat (Potenciação Pós-Ativação - PAP)',
    phase: 'NEURAL_OVERCOMING',
    durationSeconds: 5,
    sets: 3,
    repsOrHold: '3 tentativas x 5 segundos de INTENÇÃO MÁXIMA (100%)',
    purpose: 'Recrutar as unidades motoras de alto limiar (Tipo IIx) instantaneamente sem gerar acidose láctica ou dano muscular.',
    instructions: 'Posicione uma barra travada sob os pinos da gaiola (ou cinta/toalha inelástica). Empurre com 100% de esforço como se fosse arrancar a gaiola do chão por exatamente 5 segundos.',
  },
  {
    id: 'prime_4',
    name: 'Submaximal Elastic Pogo Jumps com Aceleração de Braços',
    phase: 'PAP_POTENTIATION',
    durationSeconds: 30,
    sets: 2,
    repsOrHold: '8 saltos elásticos rápidos + 1 salto vertical máximo de teste',
    purpose: 'Sincronizar a cadência de braços e liberar a potenciação neuromuscular para o jogo.',
    instructions: 'Rebotes curtos e rápidos, finalizando na 8ª repetição com uma decolagem vertical potente. Sensação de "pernas leves e elásticas".',
  },
];
